name = "pipes"
version = "0.1.0"
defaultTargets = ["Pipes"]
# moreLinkArgs = [
#   "-L./.lake/packages/LeanCopilot/.lake/build/lib",
#   "-lctranslate2",
# ]

[[lean_lib]]
name = "Pipes"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

# [[require]]
# name = "LeanCopilot"
# git = "https://github.com/lean-dojo/LeanCopilot.git"
# rev = "main"

# lake exe test-pipes
[[lean_exe]]
name = "test-pipes"
root = "Main"
