name = "pipes"
version = "0.1.0"
defaultTargets = ["Pipes"]

[[lean_lib]]
name = "Pipes"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

# [[lean_exe]]
# name = "pipes"
# root = "Main"
